#!/bin/sh

mkdir_maybe() {
	if [ -d "$1" ]; then
		return 0
	fi

	mkdir -p "$1"
}

usage() {
	echo "usage: rfc [-s] number" 1>&2
	exit 2
}

std=0
while getopts s name
do
	case $name in
	s)	std=1 ;;
	?)	usage ;;
	esac
done

shift $(($OPTIND - 1))

if [ $# -ne 1 ]; then
	usage
fi

if [ $std -eq 1 ]; then
	fmt="std/std"
else
	fmt="rfc"
fi

if [ -n "$RFCCACHE" ]; then
	mkdir_maybe "$RFCCACHE" || exit 1

	if [ $std -eq 1 ]; then
		dir="std"
	else
		dir="rfc"
	fi

	mkdir_maybe "$RFCCACHE/$dir" || exit 1

	if [ ! -f "${RFCCACHE}/${dir}/$1" ]; then
		ftp -o - "https://www.ietf.org/rfc/${fmt}$1.txt" 2>/dev/null \
			| tr -d "\\014" > "${RFCCACHE}/${dir}/$1" || exit 1
	fi

	less "${RFCCACHE}/${dir}/$1" || exit 1
else
	ftp -o - "https://www.ietf.org/rfc/${fmt}$1.txt" 2>/dev/null \
		| tr -d "\\014" | less || exit 1
fi
