#!/bin/sh

# Copyright (c) 2024 Henry Ford <fordhenry2299@gmail.com>

# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

maketags() {
	filename="$1"

	# PREFIX is filled in by the Makefile, unless we are running
	# ./rfc in the source directory, in which case we can use
	# the local rfctags binary.
	if [ -z "${PREFIX}" ]; then
		./rfctags "$1" || exit 1
	else
		${PREFIX}/libexec/rfctags "$1" || exit 1
	fi
}

pager() {
	tags="$1"
	filename="$2"

	pager="${PAGER:=less}"
	if [ "$pager" != "less" ] && [ "$pager" != "more" ]; then
		# Pagers other than less(1) and more(1) dont necessarilly
		# support tags via -T, so dont pass the option.
		"${pager}" "${filename}"
	else
		"${pager}" -T "${tags}" "${filename}"
	fi

}

usage() {
	echo "usage: rfc [-s] document" 1>&2
	exit 2
}

# Needed for ftp(1) invocations
set -o pipefail

std=0
while getopts s name; do
	case $name in
	s) std=1 ;;
	?) usage ;;
	esac
done

shift $(($OPTIND - 1))

if [ $# -ne 1 ]; then
	usage
fi

document="$1"

if [ $std -eq 1 ]; then
	url="https://www.ietf.org/rfc/std/std$document.txt"
else
	url="https://www.ietf.org/rfc/rfc$document.txt"
fi

if [ -n "$RFCCACHE" ]; then
	[ -d "$RFCCACHE" ] || mkdir "$RFCCACHE" || exit 1

	if [ $std -eq 1 ]; then
		dir="$RFCCACHE/std"
	else
		dir="$RFCCACHE/rfc"
	fi

	[ -d "$dir" ] || mkdir "$dir" || exit 1

	file="$dir/$document"
	tags="$dir/$document.tags"
	if [ ! -f "$file" ]; then
		tmp="$(mktemp)" || exit 1
		trap 'rm "$tmp"' EXIT
		ftp -V -o - "$url" | tr -d '\014' > "$tmp" || exit 1
		mv "$tmp" "$file" || exit 1
		trap "" EXIT

	fi

	# Invocations from before ctags support was added would not
	# have created this file, so we have to do it even if we already
	# downloaded the rfc.
	if [ ! -f "$tags" ]; then
		tmp="$(mktemp)" || exit 1
		trap 'rm "$tmp"' EXIT
		maketags "$file" > "$tmp"
		mv "$tmp" "$tags"
		trap "" EXIT
	fi

	pager "$tags" "$file" || exit 1
else
	file="$(mktemp)" || exit 1
	trap 'rm "$file"' EXIT
	ftp -V -o - "$url" | tr -d '\014' > "$file" || exit 1

	tags="$(mktemp)" || exit 1
	trap 'rm "$file" "$tags"' EXIT
	maketags "$file" > "$tags"

	pager "$tags" "$file" || exit 1
fi
