#!/bin/sh

# Copyright (c) 2024 Henry Ford <fordhenry2299@gmail.com>

# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

usage() {
	echo "usage: rfc [-s] document" 1>&2
	exit 2
}

# Needed for ftp(1) invocations
set -o pipefail

std=0
while getopts s name; do
	case $name in
	s) std=1 ;;
	?) usage ;;
	esac
done

shift $(($OPTIND - 1))

if [ $# -ne 1 ]; then
	usage
fi

document="$1"

if [ $std -eq 1 ]; then
	url="https://www.ietf.org/rfc/std/std$document.txt"
else
	url="https://www.ietf.org/rfc/rfc$document.txt"
fi

if [ -n "$RFCCACHE" ]; then
	[ -d "$RFCCACHE" ] || mkdir "$RFCCACHE" || exit 1

	if [ $std -eq 1 ]; then
		dir="$RFCCACHE/std"
	else
		dir="$RFCCACHE/rfc"
	fi

	[ -d "$dir" ] || mkdir "$dir" || exit 1

	file="$dir/$document"
	if [ ! -f "$file" ]; then
		tmp="$(mktemp)" || exit 1
		trap 'rm "$tmp"' EXIT
		ftp -V -o - "$url" | tr -d '\014' > "$tmp" || exit 1
		mv "$tmp" "$file" || exit 1
		trap "" EXIT
	fi

	less "$file" || exit 1
else
	file="$(mktemp)" || exit 1
	trap 'rm "$file"' EXIT
	ftp -V -o - "$url" | tr -d '\014' > "$file" || exit 1
	less "$file" || exit 1
fi
